import PolygonSetReconstruction

open Set MergedNormalPrismatoid PolygonSetReconstruction

namespace PolygonSetReconstructionSanity

noncomputable def pt (x y : ℝ) : Plane := WithLp.toLp 2 ![x, y]

/-- Deliberately unordered: an interior point first, then alternating corners,
with a straight-through boundary sample. No boundary order is supplied. -/
noncomputable def cloud : Finset Plane :=
  {pt (1/2) (1/2), pt 1 1, pt 0 0, pt 1 0, pt (1/2) 0, pt 0 1}

lemma cloud_interior : (interior (convexHull ℝ (↑cloud : Set Plane))).Nonempty := by
  classical
  have hzero : (0 : Plane) ∈ (↑cloud : Set Plane) := by
    have heq : pt 0 0 = 0 := by ext i; fin_cases i <;> simp [pt]
    simp [cloud, ← heq]
  have he0 : pt 1 0 ∈ (↑cloud : Set Plane) := by simp [cloud]
  have he1 : pt 0 1 ∈ (↑cloud : Set Plane) := by simp [cloud]
  have hs : Submodule.span ℝ (↑cloud : Set Plane) = ⊤ := by
    apply top_unique
    intro x _
    have hx : x = (x 0) • pt 1 0 + (x 1) • pt 0 1 := by
      ext i
      fin_cases i <;> simp [pt]
    rw [hx]
    exact Submodule.add_mem _
      (Submodule.smul_mem _ _ (Submodule.subset_span he0))
      (Submodule.smul_mem _ _ (Submodule.subset_span he1))
  have ha : (affineSpan ℝ (↑cloud : Set Plane) : Set Plane) =
      (Submodule.span ℝ (↑cloud : Set Plane) : Set Plane) := by
    simpa only [Set.insert_eq_of_mem hzero] using
      (affineSpan_insert_zero (k := ℝ) (↑cloud : Set Plane))
  apply interior_convexHull_nonempty_iff_affineSpan_eq_top.mpr
  apply SetLike.coe_injective
  rw [ha, hs]
  rfl

/-- The cloud is genuinely redundant, proved in Lean rather than inferred from
its name: its middle point is generated by two retained corners. -/
lemma cloud_redundant : pt (1/2) (1/2) ∈
    convexHull ℝ (↑(cloud.erase (pt (1/2) (1/2))) : Set Plane) := by
  classical
  have h0 : pt 0 0 ∈ cloud.erase (pt (1/2) (1/2)) := by
    simp only [Finset.mem_erase]
    constructor
    · intro h
      have := congrArg (fun p : Plane => p 0) h
      norm_num [pt] at this
    · simp [cloud]
  have h1 : pt 1 1 ∈ cloud.erase (pt (1/2) (1/2)) := by
    simp only [Finset.mem_erase]
    constructor
    · intro h
      have := congrArg (fun p : Plane => p 0) h
      norm_num [pt] at this
    · simp [cloud]
  have hh := (convex_convexHull ℝ (↑(cloud.erase (pt (1/2) (1/2))) : Set Plane))
    (subset_convexHull ℝ _ h0) (subset_convexHull ℝ _ h1)
    (show (0 : ℝ) ≤ 1/2 by norm_num) (show (0 : ℝ) ≤ 1/2 by norm_num)
    (show (1/2 : ℝ) + 1/2 = 1 by norm_num)
  convert hh using 1
  ext i
  fin_cases i <;> norm_num [pt]

/-- An actual application of the universal constructor, with exact equality to
the original redundant finite point cloud. -/
theorem cloud_reconstruction :
    ∃ k : ℕ, ∃ hk : NeZero k, ∃ P : ReducedConvexPolygon k,
      P.body = convexHull ℝ (↑cloud : Set Plane) ∧
      range P.vertex ⊆ (↑cloud : Set Plane) :=
  exists_reduced_polygon_of_finite_hull cloud cloud_interior

end PolygonSetReconstructionSanity

#check PolygonSetReconstructionSanity.cloud_reconstruction
#print axioms PolygonSetReconstructionSanity.cloud_interior
#print axioms PolygonSetReconstructionSanity.cloud_redundant
#print axioms PolygonSetReconstructionSanity.cloud_reconstruction
