"""Regenerate test_review_stage3_adapted.py from System's verbatim Stage 3 review cases.

Every change is a literal, counted substitution listed in ADAPTER below; no assertion is edited.
Usage (from engine/):  python -m tests.two_rim_dev.make_review_stage3_adapted
"""
import re
from pathlib import Path

ENGINE = Path(__file__).resolve().parents[2]
SOURCE = ENGINE / "review-cases" / "stage3-review" / "test_stage3_regressions.py"
TARGET = Path(__file__).resolve().parent / "test_review_stage3_adapted.py"

HEADER = '''"""ADAPTED copy of System's Stage 3 review cases (sanitized copy of the verbatim original at review-cases/stage3-review/;
original Git blob 0ec7cd0114fee65314242182269939cf357937cf, retained privately). Generated by make_review_stage3_adapted.py.

Mechanical changes only (see ADAPTER-NOTE.md in the review):
1. Checker version 1 -> 2 for two_rim.check.development and two_rim.check.trimmed_development,
   whose claim contracts changed in the S02-S04 repair (two_rim.check.cut is unchanged at v1).
2. registry() gains with_stage2=False; test_S01_trim_summary_keeps_failed_parent_copy_obligation
   registers the real Stage 2 v2 source/material checkers, so its source/material prerequisites
   legitimately pass and the development cut-copy failure is what blocks the source-linked pass.
3. S03 reads the renamed receipt field lifted_total_turn_sign (the v1 field defect_sign no longer
   exists; it conflated the principal rotation with the lifted sum).
No assertion is removed or weakened.

Original docstring follows:
'''

ADAPTER = [
    (r"('two_rim\.check\.(?:development|trimmed_development)',\s*)1\b", r"\g<1>2", 8),
    (r"def registry\(change_development=None\):", "def registry(change_development=None, with_stage2=False):", 1),
    (r"    register_development_checkers\(r\)\n    return r\n",
     "    register_development_checkers(r)\n    if with_stage2:\n"
     "        from glab.check.two_rim_source import register_checkers as register_stage2_checkers\n"
     "        register_stage2_checkers(r)\n    return r\n", 1),
    (r"run,s,m=source_material\(registry\(change_copy\)\)", "run,s,m=source_material(registry(change_copy, with_stage2=True))", 1),
    (r"\.get\('defect_sign'\)", ".get('lifted_total_turn_sign')", 1),
]


def build() -> str:
    text = SOURCE.read_text(encoding="utf-8").replace("\r\n", "\n")
    assert text.startswith('"""')
    for pattern, repl, count in ADAPTER:
        text, n = re.subn(pattern, repl, text)
        assert n == count, (pattern, n, count)
    return HEADER + text[3:]


if __name__ == "__main__":
    TARGET.write_text(build(), encoding="utf-8", newline="\n")
    print("wrote", TARGET)
