"""ADAPTED copy of System's Stage 3 review cases (sanitized copy of the verbatim original at review-cases/stage3-review/;
original Git blob 0ec7cd0114fee65314242182269939cf357937cf, retained privately). Generated by make_review_stage3_adapted.py.

Mechanical changes only (see ADAPTER-NOTE.md in the review):
1. Checker version 1 -> 2 for two_rim.check.development and two_rim.check.trimmed_development,
   whose claim contracts changed in the S02-S04 repair (two_rim.check.cut is unchanged at v1).
2. registry() gains with_stage2=False; test_S01_trim_summary_keeps_failed_parent_copy_obligation
   registers the real Stage 2 v2 source/material checkers, so its source/material prerequisites
   legitimately pass and the development cut-copy failure is what blocks the source-linked pass.
3. S03 reads the renamed receipt field lifted_total_turn_sign (the v1 field defect_sign no longer
   exists; it conflated the principal rotation with the lifted sum).
No assertion is removed or weakened.

Original docstring follows:
System's Stage 3 review cases for commit-47 (no production changes).

The source-linked search expectations are integration requirements. Intrinsic
geometry of a wrong-source body can still be valid. The other cases pin the
already documented development/trim meaning and diagnostic distinctions.

Run from an engine checkout, with its numeric dependencies:
  GLAB_ENGINE=/path/to/engine python -m pytest -q test_stage3_regressions.py
"""
from __future__ import annotations
import copy
import math
import os
import sys
from dataclasses import replace
from pathlib import Path

import pytest

ENGINE = Path(os.environ.get('GLAB_ENGINE', Path.cwd())).resolve()
sys.path.insert(0, str(ENGINE))

from glab.core.registry import Registry, ActionSpec, StateDraft, RegistryError
from glab.core.runfile import Run, load_run, replay
from glab.two_rim.actions import register_actions
from glab.two_rim.dev_actions import register_development_actions
from glab.two_rim.develop import develop_static
from glab.two_rim.trim import apply_trim
from glab.two_rim.material import build_material
from glab.two_rim.source import normalize_source
from glab.two_rim.search import enumerated_candidate_search
from glab.check.two_rim_development import register_development_checkers, NUMERICAL, DIAGNOSTICS

SQ = [[0, 0], [0, 2], [2, 2], [2, 0]]
BASE = dict(top=SQ, bottom=SQ, height='3', input_kind='cyclic_boundary')
E11 = dict(top=[[-40,-28], [31,-11], [16,27], [-15,50]],
           bottom=[[-85,60], [-26,-53], ['1693/100','-2569/50'],
                   ['564/25','-4993/100'], ['303/10','-77/2'], [60,74], [18,91]],
           height='1/10000', input_kind='cyclic_boundary')
ACTION_NAMES = ['two_rim.cut.open', 'two_rim.develop.static', 'two_rim.trim.apply']


def registry(change_development=None, with_stage2=False):
    original = Registry()
    register_development_actions(original)
    r = Registry()
    register_actions(r)
    for name in ACTION_NAMES:
        spec = original.action(name, 1)
        if name == 'two_rim.develop.static' and change_development:
            def bad(st, params, seed):
                payload = develop_static(st['payload'])
                change_development(payload)
                return StateDraft('two_rim.development', payload, 'mixed')
            spec = replace(spec, fn=bad, revision='review-fault-injected-development')
        r.register_action(spec)
    register_development_checkers(r)
    if with_stage2:
        from glab.check.two_rim_source import register_checkers as register_stage2_checkers
        register_stage2_checkers(r)
    return r


def source_material(r, params=BASE, builder='two_rim.material.build'):
    run = Run(r)
    s = run.apply('two_rim.source.normalize', 1, copy.deepcopy(params))['output']
    got = run.apply(builder, 1, {}, s)
    assert got['status'] == 'succeeded', got
    return run, s, got['output']


def cut_dev(run, m, seam='E0'):
    c = run.apply('two_rim.cut.open', 1, {'seam': seam}, m)['output']
    d = run.apply('two_rim.develop.static', 1, {}, c)['output']
    return c, d


def by_claim(evs):
    return {e['claim']: e for e in evs}


def local_scan(run, m, delta):
    """Control-only intrinsic geometry checks, not a source-linked publication summary."""
    from glab.core.evidence import Requirement
    from glab.two_rim.search import CUT_OBLIGATIONS, DEVELOPMENT_OBLIGATIONS, TRIM_OBLIGATIONS
    rows = []
    for edge in run.get(m)['payload']['hinges']:
        c,d = cut_dev(run,m,edge['id'])
        t = run.apply('two_rim.trim.apply',1,{'delta':delta},d)['output']
        run.check('two_rim.check.cut',1,c,{})
        run.check('two_rim.check.development',2,d,{})
        run.check('two_rim.check.trimmed_development',2,t,{})
        cut_req = [Requirement(x,c) for x in CUT_OBLIGATIONS]
        rows.append(dict(seam=edge['id'],cut=c,development=d,trimmed=t,
            full_obligations=run.summarize(cut_req+[Requirement(x,d) for x in DEVELOPMENT_OBLIGATIONS])['outcome'],
            trimmed_obligations=run.summarize(cut_req+[Requirement(x,t) for x in TRIM_OBLIGATIONS])['outcome']))
    return {'results':rows}


def test_control_square_local_geometry_and_replay(tmp_path):
    r = registry()
    run, s, m = source_material(r)
    scan = local_scan(run, m, '1/4')
    assert len(scan['results']) == 4
    assert all(row['full_obligations'] == row['trimmed_obligations'] == 'pass' for row in scan['results'])
    f = tmp_path/'square.json'
    out = replay(load_run(f, expected_digest=run.save(f)), r)
    assert out['outcome'] == 'reproduced' and out['run_digest_reproduced']


def test_control_e11_documented_current_seams_and_overlap_pair():
    run, s, m = source_material(registry(), E11)
    scan = local_scan(run, m, '1/10000')
    rows = {row['seam']: row for row in scan['results']}
    assert {k for k,v in rows.items() if v['trimmed_obligations'] == 'fail'} == {'E3','E8','E9','E10'}
    assert {k for k,v in rows.items() if v['trimmed_obligations'] == 'unknown'} == {'E0','E1','E2','E4','E5','E6','E7'}
    ev = by_claim(run.check('two_rim.check.trimmed_development', 2, rows['E9']['trimmed'], {}))
    pairs = ev[NUMERICAL[4]]['receipt']['rows']
    assert any(set(p['pair']) == {'F10', 'F7'} and p['outcome'] == 'fail' for p in pairs)
    assert ev[NUMERICAL[4]]['receipt']['pairs_checked'] == 55
    assert ev[NUMERICAL[4]]['receipt']['adjacent_pairs_checked'] == 10
    assert ev[NUMERICAL[4]]['receipt']['adjacent_pairs_skipped'] == 0


def test_control_dropped_translation_is_not_accepted():
    def remove_offsets(p):
        for m in p['maps']:
            m['offset'] = [0.0, 0.0]
    run,s,m = source_material(registry(remove_offsets))
    c,d = cut_dev(run,m)
    ev = by_claim(run.check('two_rim.check.development',2,d,{}))
    assert ev[NUMERICAL[0]]['outcome'] == 'pass'
    assert ev[NUMERICAL[3]]['outcome'] == 'fail'


def source_linked(row, kind):
    # A repair may preserve explicitly local summaries and add a separate
    # source-linked aggregate, rather than silently changing their meaning.
    return row.get(f'source_linked_{kind}_obligations', row.get(f'{kind}_obligations'))


def test_S01_source_linked_search_cannot_omit_source_correspondence():
    r=registry()
    r.register_action(ActionSpec('review.wrong.material',1,'two_rim.source',{},'review-1',
        lambda st,p,seed: StateDraft('two_rim.material',build_material(normalize_source(**dict(BASE,height='4'))),'exact')))
    run,s,m=source_material(r,builder='review.wrong.material')
    assert run.get(s)['payload']['normalized']['height'] != run.get(m)['payload']['height']
    # Missing source/material evidence must not be reported as a complete source-linked pass.
    # Rejection for unavailable prerequisite checkers is acceptable at this boundary.
    try:
        rows=enumerated_candidate_search(run,m,'1/4')['results']
    except RegistryError as exc:
        assert 'checker' in str(exc).lower()
        return
    assert rows and all(source_linked(row,'full') != 'pass' and source_linked(row,'trimmed') != 'pass' for row in rows)


def test_S01_trim_summary_keeps_failed_parent_copy_obligation():
    def change_copy(p):
        p['cut']['schema'] = 'two_rim.cut/99'
    run,s,m=source_material(registry(change_copy, with_stage2=True))
    rows=enumerated_candidate_search(run,m,'1/4')['results']
    assert all(row['full_claims']['two_rim.development.cut_copy_matches_parent'] == 'fail' for row in rows)
    assert all(source_linked(row,'trimmed') != 'pass' for row in rows)


def test_S02_changed_map_convention_is_not_a_supported_schema():
    run,s,m=source_material(registry(lambda p:p.update(map_convention='image = linear @ [x, y, z] - offset')))
    c,d=cut_dev(run,m)
    ev=by_claim(run.check('two_rim.check.development',2,d,{}))
    assert ev['two_rim.development.record_schema']['outcome'] != 'pass'


@pytest.mark.parametrize('mutation', ['height_parameter','boolean_coordinate','numeric_coordinate'])
def test_S02_trim_interpretation_and_exact_number_contract(mutation):
    r=registry();run,s,m=source_material(r);c,d=cut_dev(run,m)
    def builder(st,p,seed):
        trim=apply_trim(st['payload'],'1/4')
        if mutation=='height_parameter':
            trim['height_parameter']='absolute z, not normalized height'
        else:
            point=next(v for v in trim['trim_points'].values() if v['xyz'][0]=='0')
            point['xyz'][0]=False if mutation=='boolean_coordinate' else 0.0
        return StateDraft('two_rim.trimmed_development',trim,'mixed')
    r.register_action(ActionSpec('review.trim',1,'two_rim.development',{},'review-1',builder))
    t=run.apply('review.trim',1,{},d)['output']
    ev=by_claim(run.check('two_rim.check.trimmed_development',2,t,{}))
    assert ev['two_rim.trim.record_schema']['outcome'] != 'pass'


def test_S03_principal_angle_is_not_the_lifted_total_turn_sign():
    run,s,m=source_material(registry(),E11);c,d=cut_dev(run,m,'E9')
    ev=by_claim(run.check('two_rim.check.development',2,d,{}))[DIAGNOSTICS[2]]
    q=run.get(d)['payload']['generator']['sum_q']
    assert q < -math.pi  # Stored generator sum is about -6.2076, not +0.07558.
    # Report the numerical lifted sign correctly, or leave it unknown pending an independent lift check.
    assert ev['receipt'].get('lifted_total_turn_sign') in (None,'unknown','negative')


def test_S04_numerical_tolerance_is_in_the_core_policy_field():
    run,s,m=source_material(registry());c,d=cut_dev(run,m)
    evs=run.check('two_rim.check.development',2,d,{})
    assert all(e['tolerances'] is not None for e in evs if e['claim'] in NUMERICAL)
