"""Regenerate test_review_stage4a_adapted.py from System's verbatim Stage 4A review cases.

Every change is a literal, counted substitution listed in ADAPTER below; no assertion is edited.
Usage (from engine/):  python probes/stage4a/tests/review_env/make_review_stage4a_adapted.py
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
SOURCE = HERE.parents[1] / "review-cases" / "stage4a-review" / "test_stage4a_review.py"
TARGET = HERE / "test_review_stage4a_adapted.py"

HEADER = '''"""ADAPTED copy of System's Stage 4A review cases (sanitized copy of the verbatim original at
probes/stage4a/review-cases/stage4a-review/test_stage4a_review.py; original Git blob 9b141bce2f6c9a937455bb5349cc1bf26d3a0d66, retained privately).
Generated by make_review_stage4a_adapted.py (see ADAPTER-NOTE.md in the review).

One mechanical change: make_bundle() builds the repaired re-checker's bound bundle
(schema stage4a.recheck_bundle/2: state records, subject spec and ID, declared verdict on D) with the
probe's exporter, instead of the old unbound layout that the repaired re-checker deliberately rejects.
Every test body and assertion is unchanged; each A03 mutation is applied to that genuinely valid bundle.

Original docstring follows:
'''

NEW_MAKE_BUNDLE = '''def make_bundle(prepared, seams=('E9',)):
    # ADAPTER: bound v2 bundle from the probe's exporter (the unbound layout is rejected by design).
    from probes.stage4a.run_probe import recheck_bundle
    return recheck_bundle(prepared, list(seams))
'''

ADAPTER = [
    (r"def make_bundle\(prepared, seams=\('E9',\)\):\n(?:    .*\n)+?    return bundle\n", NEW_MAKE_BUNDLE, 1),
]


def build() -> str:
    text = SOURCE.read_text(encoding="utf-8").replace("\r\n", "\n")
    assert text.startswith('"""')
    for pattern, repl, count in ADAPTER:
        text, n = re.subn(pattern, lambda m: repl, text)
        assert n == count, (pattern, n, count)
    return HEADER + text[3:]


if __name__ == "__main__":
    TARGET.write_text(build(), encoding="utf-8", newline="\n")
    print("wrote", TARGET)
